---
rules:
  no-use-before-define:
    - 2
  max-len:
    - 2
    - 140
env:
  es6: true
  browser: true
  commonjs: true
  node: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
extends:
  - eslint:recommended
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
